--- #YAML:1.0
name:                Apache-Dispatch
version:             0.10_01
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    mod_perl:                      1.2401
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
