--- #YAML:1.0
name:               Apache-Dispatch
version:            0.11
abstract:           call PerlHandlers with the ease of Registry scripts
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    mod_perl:  1.30
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
